package pl.investadvisor.datascraper.model;

public enum CommoditySector {
    FINANCE, ENERGY, HEALTHCARE, TRADE_AND_SERVICES, CHEMICAL, GAMING, HIGH_TECH_OR_IT, TELECOM, BIO_TECH, MOTORIZATION,
    INDUSTRY, MINING, AGRO, CONSTRUCTION, PHOTOVOLTAICS
}
