package pl.investadvisor.datascraper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;
import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Builder
@Data
@DynamoDBTable(tableName = "CommodityPrice")
public class CommodityPrice implements Serializable {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "commodityPriceId")
    private String commodityPriceId;

    @NonNull
    private String commodityId;

    @NonNull
    private BigDecimal price;

    @NonNull
    private String currency;

    @DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS")
    @NonNull
    private Date date;

}
