package pl.investadvisor.datascraper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

import java.math.BigDecimal;
import java.util.Date;

@AllArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "Commodity")
@NoArgsConstructor
public class Commodity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "commodityId")
    private String commodityId;

    @NonNull
    private String index;

    @DynamoDBTypeConvertedEnum
    @NonNull
    private ScrapingStrategy scrapingStrategy;

    private String dataSource;

    @DynamoDBTypeConvertedEnum
    @NonNull
    private CommodityType commodityType;

    @DynamoDBTypeConvertedEnum
    @NonNull
    private CommoditySector commoditySector;

    @DynamoDBTypeConvertedEnum
    private RawMaterial rawMaterial;

    @NonNull
    private String currency;

    @NonNull
    private BigDecimal price;

    private String comment;

    @DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS")
    @NonNull
    private Date lastScrapingDate;
}
