package pl.investadvisor.datascraper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Data;
import lombok.NonNull;

import java.io.Serializable;
import java.math.BigDecimal;

@Builder
@Data
@DynamoDBTable(tableName = "CommodityPrice")
public class CommodityPrice implements Serializable {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "commodityPriceId")
    private String commodityPriceId;

    @NonNull
    private String commodityId;

    @NonNull
    private BigDecimal price;

    @NonNull
    private String currency;

    @NonNull
    private Long time;

}
