package pl.investadvisor.datascraper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@AllArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "Commodity")
@NoArgsConstructor
public class Commodity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "commodityId")
    private String commodityId;

    @NonNull
    private String index;

    @DynamoDBTypeConvertedEnum
    @NonNull
    private ScrapingStrategy scrapingStrategy;

    private String dataSource;

    @DynamoDBTypeConvertedEnum
    @NonNull
    private CommodityType commodityType;
}
