package pl.investadvisor.datascraper.model;

public enum CommoditySector {
    FINANCE, MINING_AND_ENERGY, HEALTHCARE, TRADE_AND_SERVICES, CHEMICAL, GAMING, HIGH_TECH_AND_IT, TELECOM, BIO_TECH, MOTORIZATION,
    INDUSTRY, AGRO, CONSTRUCTION, PHOTOVOLTAICS
}
