package pl.investadvisor.datascraper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

@Builder
@Data
@DynamoDBTable(tableName = "commodityPrice")
public class CommodityPrice implements Serializable {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "commodityPriceId")
    private String commodityPriceId;
    @DynamoDBAttribute
    private String index;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private BigDecimal price;
    @DynamoDBAttribute
    private String currency;

}
