package pl.investadvisor.datascraper.model;

public enum CommoditySector {
    FINANCE, ENERGY, HEALTHCARE, TRADE_AND_SERVICES, CHEMICAL, GAMING, IT, TELECOM, HIGH_TECH, BIO_TECH, MOTORIZATION,
    INDUSTRY, RARE_EARTH_MINING, METAL_MINING, AGRO, CONSTRUCTION
}
